### ISSUE TITLE
Alertmanager notification service doesn't work

### ISSUE THREAD

**Issue by rgeraskin** [argoproj/notifications-engine#143]
Using notification controller bundled in argocd:v2.4.8 with config:
```
  service.alertmanager: |
    targets:
      - webhook.site:443
    scheme: https
    apiPath: /0be1114e-c211-4fb3-bb47-908e51aa9675/api/events
```

and app annotation
```
notifications.argoproj.io/subscribe.on-sync-succeeded.alertmanager: ""
```

I can't get any notifications on my endpoint. I can see this error in logs:
```
time="2023-01-06T20:59:45Z" level=error msg="Failed to notify recipient {alertmanager } defined in resource argocd/guestbook: notification alertmanager no config" resource=argocd/guestbook
```
