### ISSUE TITLE
Email Notifications don't support multiple to addresses

### ISSUE THREAD

**Issue by gokulav137** [argoproj/notifications-engine#222]
Currently each recipients email address would be send a separate email address.

So an email will be sent out for each recipient email1@gmail.com and email2@gmail.com for the following:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: another
  annotations:
    notifications.argoproj.io/subscriptions: |
      - trigger: [on-cert-ready]
        destinations:
          - service: email
            recipients: [email1@gmail.com, email2@gmail.com]
spec:
  secretName: something
  issuerRef:
    name: letsencrypt-staging
  emailAddresses:
    - email1@gmail.com
```
### Proposition

I would like to propose adding a feature to support comma separated email addresses so that we can we can do the below:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: another
  annotations:
    notifications.argoproj.io/subscriptions: |
      - trigger: [on-cert-ready]
        destinations:
          - service: email
            recipients: ["email1@gmail.com,email2@gmail.com", email2@gmail.com]
spec:
  secretName: something
  issuerRef:
    name: letsencrypt-staging
  emailAddresses:
    - email1@gmail.com
```
Here one email would be sent with only email2@gmail.com as recipient and another with both email1@gmail.com and email2@gmail.com.

This can be done by introducing the following change in https://github.com/argoproj/notifications-engine/blob/master/pkg/services/email.go#L77-L84:
 ```go
 to := String.Split(dest.Recipient, ",")
 email := smtp.New(smtp.Options{
 ........
 ........
 }).WithSubject(subject).WithBody(body).To(to[0], to[1:]...)
 ```
 This shouldn't break any existing functionality. I have tested this out locally.

**I can raise a PR if this seems useful.**

_Originally posted by @gokulav137 in https://github.com/argoproj/argo-events/pull/2793#discussion_r1324807734_
