### ISSUE TITLE
Add support for github commit status notifications with multi source apps

### ISSUE THREAD

**Issue by CarlosLanderas** [argoproj/notifications-engine#224]
As described in this [issue](https://github.com/argoproj/argo-cd/issues/15617), it looks like the github notification service has not implemented the support for multi source applications and it's returning an out of range error as it's only considering the repoURL inside single source definition.

It looks like it's working with a **[fixed repoUrl template](https://github.com/argoproj/notifications-engine/blob/master/pkg/services/github.go#L64)**

**Comment by Amphaal** [comment]
It is ! I think a workaround would be to set a custom `repoURLPath` on your templates:

```
github:
  repoURLPath: "{{.app.metadata.annotations.argocdRepoURL}}"
```

And then set this annotation on all `Application` annotations / `ApplicationSet` templates annotations:

```
  annotations:
    # repo to which push notifications
    argocdRepoURL: "{{ iac__github_org_url }}/{{ argocd__app_of_apps__repo_name }}"
    #
    notifications.argoproj.io/subscribe.on-sync-running.github: ""
    notifications.argoproj.io/subscribe.on-sync-failed.github: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.github: ""
    notifications.argoproj.io/subscribe.on-sync-status-unknown.github: ""
    notifications.argoproj.io/subscribe.on-deployed.github: ""
```

I havent been able to use something like `github.notifications.argoproj.io/repo-url` instead of `argocdRepoURL` tho, I think there is something about `html/template` that prevents me from reading annotations fields with slashes and dots
