### ISSUE TITLE
Support for Atlassian's Jira

### ISSUE THREAD

**Issue by alexmt** [argoproj/notifications-engine#24]
By @AlexDHoffer: https://github.com/argoproj-labs/argocd-notifications/issues/240

Some existing CD systems e.g. Jenkins can post build results to Jira issues as well as natively link commits in the build to those issues. See here for details: https://plugins.jenkins.io/jira/

This is a slick feature for a CD system and since Atlassian's Jira is in such widespread usage these days it would be cool to have something similar, where ArgoCD can key off a Jira issue tag in a commit message and post when a successful sync of that tag occurred back to the issue itself in Jira.

**Comment by onmomo** [comment]
Has anybody worked around this? Thinking about a PostSync hook but this would require a dedicated pod to connect with the Jira API and a solution to get the git diff of the sync inside this pod.

**Comment by JeffreyGarrett** [comment]
Hello Is there a status on this for bringing this in?  Either that or possibly suggestions on how it could be incorporated?

**Comment by Aditya-velotio** [comment]
Hi , any updates here?

**Comment by nweiler** [comment]
Bump

**Comment by mjallday** [comment]
Where would ArgoCD get the deployment information from? I'm looking at the [deployment API](https://developer.atlassian.com/cloud/jira/software/modules/deployment/) and you need to pass an issue key to annotate the Jira issue with the deployment information. 

It's not clear where this would come from. Potentially it could be build into the container as a label I guess?

**Comment by johan-lejdung** [comment]
> Where would ArgoCD get the deployment information from? I'm looking at the [deployment API](https://developer.atlassian.com/cloud/jira/software/modules/deployment/) and you need to pass an issue key to annotate the Jira issue with the deployment information.
> 
> It's not clear where this would come from. Potentially it could be build into the container as a label I guess?

We have that information attached to commits in the Git repo used to build the docker image Argo uses. But that repo is of course not connected to Argo in any way. If this is a common setup one idea would be to link a repo to read issue keys from commit messages

**Comment by jessesuen** [comment]
In case it helps others, I found this example in [slack](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1666843221817629):

```yaml
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - atlassian
      when: app.status.operationState.phase in ['Succeeded']
  template.atlassian: |
    webhook:
      atlassian:
        method: POST
        body: |
           {"fields": {"project":{"key": "OP"},"summary": "please ignore {{.app.metadata.name}}","description": "argocd notification check this out {{.context.argocdUrl}}/applications/{{.app.metadata.name}} is in status {{.app.status.sync.status}}","issuetype": {"name": "Bug"},"components": [{"name" : "OES"}],"priority": { "name": "Low"}}}
  service.webhook.atlassian: |
    url: https://devops.atlassian.net/rest/api/2/issue/
    basicAuth:
      username: $jira-username
      password: $jira-password
    headers:
    - name: Content-Type
      value: application/json
```
