### ISSUE TITLE
How to use the engine as a general purpose notification service ?

### ISSUE THREAD

**Issue by sarathmaf** [argoproj/notifications-engine#31]
Is there any example I can trigger the notification with a webhook or integrated to an message queue.
The idea is to use the engine as a general purpose notification service.

Or is it achieved by adding custom Triggers ? Like

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  trigger.on-api-call: |
    - when: true
      send: [api-call-recevied]
```
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  template.app-sync-succeeded: |
    message: |
      You have received an API call with message {{get-api-request-body_or_param}}.
```
So this engine can be used behind a rest microservice.
