### ISSUE TITLE
Allow templating Slack NotifyBroadcast

### ISSUE THREAD

**Issue by mkantzer** [argoproj/notifications-engine#338]
I've got a slack notification that I send that alerts me to argocd events, and I'm using grouping keys to thread related notifications.

However, I only want to use `notifyBroadcast` under certain circumstances. 

Currently, you cannot use any templating on that field: I can't do, for example:

```
    template.app-health-degraded-every: |
      slack:
        notifyBroadcast: {{ if .isProduction }}true{{ else }}false{{ end }}
        deliveryPolicy: PostAndUpdate
```

I have to provide a concrete `true` or `false`.

I recognize that there's likely some string vs bool typing issues here, but it would be really great if we could [add some text templating](https://github.com/argoproj/notifications-engine/blob/261728a36e8357dfa7c258f7e1c4e3e763711ee1/pkg/services/slack.go#L32-L45) to include notifyBroadcast. (And maybe deliveryPolicy?)

I'm also happy to have this be accomplished in any other way (perhaps a new field `notifyBroadcastExpr` where you can provide an expr test, similar to how the triggers are executed?), as long as I can re-use a template but change these settings.
