### ISSUE TITLE
`awssqs` notification service failed due to `InvalidClientTokenId`

### ISSUE THREAD

**Issue by afzal442** [argoproj/notifications-engine#382]
After following the docs along with setting up the aws configuration, awssqs notification svc is not working. 
`aws sqs test-msg --queue-url https://sqs.eu-north-1.amazonaws.com/5xx16676xxx/test-sqs --message-body '{\"message\": \"hello\"}'`
Although I can send msg using the aws CLI, awssqs is showing up operation error on ArgoCD.

```
{"level":"info","msg":"Sending notification about condition 'on-deployment-ready.[0].9peq5YSISNPOq8LAcQOPwHydZFw' to '{awssqs }' using the configuration in namespace argocd","resource":"myapp-test","time":"2025-06-16T18:56:42Z"}
{"level":"error","msg":"Got an error getting the queue URL: operation error SQS: GetQueueUrl, https response error StatusCode: 403, RequestID: 94f65d0f-9493-5ce4-afxx-xxxxx, api error InvalidClientTokenId: The security token included in the request is invalid.","time":"2025-06-16T18:56:43Z"}
{"level":"error","msg":"Failed to notify recipient {awssqs } defined in resource argocd/myapp-test: operation error SQS: GetQueueUrl, https response error StatusCode: 403, RequestID: 94f65d0f-9493-5ce4-afe3-3dc5ffb8xxxx, api error InvalidClientTokenId: The security token included in the request is invalid. using the configuration in namespace argocd","resource":"myapp-test","time":"2025-06-16T18:56:43Z"}
```

ArgoCD version: 3.0.0

**Comment by afzal442** [comment]
cm and sample app are included to repro the same;

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.awssqs: |
    region: "your-region"
    queue: "test-sqs"
    account: "5xx216676xxx"
    key: $dev-sqs-id
    secret: $dev-sqs-secret

  template.on-deployment-ready: |
    message: |
      Application {{ .app.metadata.name }} is now READY!

  trigger.on-deployment-ready: |
    when: app.status.operationState.phase == 'Succeeded'
    template: on-deployment-ready
```

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-test
  annotations:
      notifications.argoproj.io/subscribe.on-deployment-ready.awssqs: ""
spec:
  destination:
    namespace: gb-test
    name: test
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
```
