### ISSUE TITLE
Debugging Tools can't read Secret

### ISSUE THREAD

**Issue by sshota0809** [argoproj/notifications-engine#51]
Hello, I have been developing and debugging my own notification-controller.

# Describe the bug

As the following document says, when I debug my own controller secret can't read anymore.

https://github.com/argoproj/notifications-engine/tree/master/examples/certmanager#debugging-tools

```
go run mydir/debug/main.go template get --config-map ./my-cm.yaml --secret ./my-secret.yaml
```

* my-cm.yaml
```
apiVersion: v1
data:
  service.slack: |
    token: $slack-token
  template.app-deployed: |
    email:
      subject: Test
    message: |
      Test Message
 manifests.
  trigger.on-deployed: |
    - description: test
      send:
      - app-deployed
      when: pod.status.phase == 'Running'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: my-cm
```

* my-secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  slack-token: aG9nZWhvZ2U=
```

# Actual behivior

the following error occurs.

```
failed to get api: file './my-secret.yaml' does not have '/Secret/my-secret'
```

# Expected behivior

list is outputed.

```
NAME          PREVIEW
app-deployed  Test Message
```

# What makes the actual behivior

As the following code, even though file is Secret this try to read ConfigMap.

https://github.com/argoproj/notifications-engine/blob/39b5307207771e962bbf468924d7a8e5727d3e1f/pkg/cmd/context.go#L65-L72

I found out the reason so I will make the PR related to this issue!
