### ISSUE TITLE
Occur runtime error: invalid memory address or nil pointer dereference in sample notifications for cert-manager 

### ISSUE THREAD

**Issue by skikkh** [argoproj/notifications-engine#61]
In order to carry out the scenario of notification using cert-manager's CRD,
I made some changes to Getting Stated's ConfigMap and built it. 
But the controller threw the following error and the notification to Slack did not work.
How should I deal with this error? The controller does not change the code, but uses the sample one.

```
cert-notifier nginx time="2021-12-28T09:19:03Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 64 [running]:
runtime/debug.Stack()
    /usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).processQueueItem.func1(0x4000315860, {0x1073ce0, 0x40000990b0})
    /go/pkg/mod/github.com/argoproj/notifications-engine@v0.3.0/pkg/controller/controller.go:200 +0x48
panic({0x10e8be0, 0x20d7530})
  usr/local/go/src/runtime/panic.go:1038 +0x224
github.com/argoproj/notifications-engine/pkg/services.(*slackService).Send(0x40001d0af0, {{0x40000a19b0, 0x27}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
    /go/pkg/mod/github.com/argoproj/notifications-engine@v0.3.0/pkg/services/slack.go:137 +0x91c
github.com/argoproj/notifications-engine/pkg/api.(*api).Send(0x4000283080, 0x40002b5650, {0x4000316e40, 0x1, 0x4}, {{0x40002c66f3, 0x5}, {0x4000040840, 0x14}})
    /go/pkg/mod/github.com/argoproj/notifications-engine@v0.3.0/pkg/api/api.go:71 +0x3f4
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).processResource(0x4000315860, {0x15ae0e8, 0x40004f4198}, 0x4000183dc0)
    /go/pkg/mod/github.com/argoproj/notifications-engine@v0.3.0/pkg/controller/controller.go:165 +0x708
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).processQueueItem(0x4000315860)
    /go/pkg/mod/github.com/argoproj/notifications-engine@v0.3.0/pkg/controller/controller.go:229 +0x38c
github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).Run.func1()
    /go/pkg/mod/github.com/argoproj/notifications-engine@v0.3.0/pkg/controller/controller.go:118 +0x34
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40000ebfc0)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155 +0x64
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x40000ebfc0, {0x1542240, 0x400012d020}, 0x1, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156 +0x94
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x40000ebfc0, 0x3b9aca00, 0x0, 0x1, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133 +0x88
k8s.io/apimachinery/pkg/util/wait.Until(0x40000ebfc0, 0x3b9aca00, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90 +0x48
created by github.com/argoproj/notifications-engine/pkg/controller.(*notificationController).Run
    go/pkg/mod/github.com/argoproj/notifications-engine@v0.3.0/pkg/controller/controller.go:117 +0x100"
```

config.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-notifications-cm
data:
  trigger.on-cert-failed: |
    - when: any(cert.status.conditions, {.reason == 'DoesNotExist' && .status == 'False'})
      send: [cert-failed]

  template.cert-failed: |
    message: |
      Certificate {{.cert.metadata.name}} is failed!

  service.slack: |
    token: $slack-token
```

**Comment by skikkh** [comment]
Related: https://github.com/argoproj/notifications-engine/pull/40
If you don't add the notifyBroadcast setting to the slack template, it will cause a panic.

Add the following settings to fix it.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-notifications-cm
data:
  trigger.on-cert-failed: |
    - when: any(cert.status.conditions, {.reason == 'DoesNotExist' && .status == 'False'})
      send: [cert-failed]

  template.cert-failed: |
    message: |
      Certificate {{.cert.metadata.name}} is failed!
    slack:
      notifyBroadcast: false

  service.slack: |
    token: $slack-token
```
