### ISSUE TITLE
Notification Engine should support a list of triggers from a single annotation

### ISSUE THREAD

**Issue by RaviHari** [argoproj/notifications-engine#64]
ref: https://github.com/argoproj/argo-rollouts/issues/1783

Notification engine should handle multiple triggers in a given annotation:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed,on-rollout-updated,on-rollout-pausedon-rollout-aborted,on-rollout-step-completed,on-scaling-replica-set.slack: ar-notifications-test
```

**Comment by alexmt** [comment]
Here it is:
```yaml
 notifications.argoproj.io/subscribe_yaml: |
    - trigger: [on-rollout-completed,on-rollout-updated,on-rollout-pausedon-rollout-aborted,on-rollout-step-completed,on-scaling-replica-set]
      destinations:
        - service: slack
          recipients: [ar-notifications-test]
```
