### ISSUE TITLE
Template nil reference

### ISSUE THREAD

**Issue by elebioda** [argoproj/notifications-engine#87]
Background: I am trying to retrieve a sub-string of the application spec source path to pass to our CI workflow using sprig split function inside the notification template. This was working perfectly fine when we had a source path like this -> charts/app1 and his worked with this template
```yaml
  template.chart-app-sync-succeeded-organization: |
    webhook:
      github-deploy-workflow:
        method: POST
        path: repos/foo/release-chart-staging.yaml/dispatches
        body: |
          {
            "ref": "main",
            "inputs": { "chart": "{{(split "/" .app.spec.source.path)._1}}", "type": "organization" }
          }
```
Problem: We have now moved our charts to sub-folders so I now need to access the second element of the split for example -> chats/global/app1
```yaml
  template.chart-app-sync-succeeded-organization: |
    webhook:
      github-deploy-workflow:
        method: POST
        path: repos/foo/release-chart-staging.yaml/dispatches
        body: |
          {
            "ref": "main",
            "inputs": { "chart": "{{(split "/" .app.spec.source.path)._2}}", "type": "organization" }
          }
```
By changing the index I no longer am able to send Webhooks to GitHub and am receiving this error.

> time="2022-04-13T02:59:42Z" level=error msg="failed to execute when condition: cannot fetch phase from <nil> (1:27)\n | app.status.operationState.phase in ['Succeeded']\n | ..........................^"

I checked what was being output by split and can clearly see the dict being generated as shown here:

> time="2022-04-13T02:57:40Z" level=error msg="Failed to notify recipient {github-deploy-workflow } defined in resource argocd/us-central1-static-fhir-resources-api: request to {{\n  \"ref\": \"main\",\n  \"inputs\": { \"chart\": \"map[_0:charts _1:organization _2:static-fhir-resources-api _3:dev]\", \"type\": \"organization\" }\n}\n

I am at a loss here... any help would be great!
