### ISSUE TITLE
Support for NewRelic - Deployment Marker API

### ISSUE THREAD

**Issue by saviogl** [argoproj/notifications-engine#93]
Support for adding New Relic as a notification service for ArgoCD notifications. New Relic has the concept of [Deployment Markers](https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/) that allows us to register a custom event as a deployment to be correlated with other observability metrics.

By adding this integration anyone using New Relic can easily rely on it to automatically create deployment markers upon application `deployments`. Within the GitOps model this will also yield markers for configuration changes beyond regular application code change which makes for a pretty holistically approach for production management and observability.

It can look something like this

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: <config-map-name>
data:
  service.mattermost: |
    apiURL: <api-url>
    apiKey: $newrelic-apiKey
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
stringData:
  newrelic-apiKey: apiKey
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.<trigger-name>.newrelic: <app-id>
```
