### ISSUE TITLE
Alert only if certain time passed

### ISSUE THREAD

**Issue by mubarak-j** [argoproj/notifications-engine#99]
I’m trying to avoid receiving false alerts/spam-like notifications when applications' health status change briefly e.g `degraded/unknown <-> healthy` often within a minute.
<img width="1166" alt="argocd-health-status-notification" src="https://user-images.githubusercontent.com/83465122/178841128-a68521e2-401f-437d-a0f3-402b49a0976a.png">

I tried to add the following time condition to alert if the app has been in the current state for 5 mins or more but it’s not working, or maybe I’m using the wrong field `app.status.operationState.startedAt` here.

```yaml
    trigger.on-health-degraded: |
      - description: Application has degraded
        oncePer: app.status.operationState.syncResult.revision
        send:
        - app-health-degraded
        when: app.status.health.status == 'Degraded' and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() >= 5
```

 I'm curious if anyone solved this issue using argocd-notifications?

**Comment by mubarak-j** [comment]
many folks reported this issue in slack as well https://cloud-native.slack.com/archives/C01UKS2NKK3/p1657184741979379

@pasha-codefresh @RaviHari @alexmt is something you can help with?

**Comment by mubarak-j** [comment]
Probably related to https://github.com/argoproj/argo-cd/issues/12169

**Comment by svghadi** [comment]
I believe the newly introduced field `app.status.health.lastTransitionTime` should help with this use-case. This field stores the timestamp of when last health status was changes.

**Comment by Andiesam** [comment]
Hey! Has anyone been able to get this to work with `app.status.health.lastTransitionTime` ? I also believe this is the key to solving the issue, but using it with the other functions doesn’t seem to work for me.
I have tried the following configurations:
```
trigger.on-health-degraded: |
    - description: Application health has degraded
      when: app.status.health.status in ['Degraded'] and app.metadata.name not in ['BrokenAppIcanIgnore'] and time.Parse(app.status.health.lastTransitionTime).Add(2 * time.Minute).Before(time.Now())
      send:
      - on-health-degraded`
```
 and this at some point 
```
trigger.on-health-degraded: |
        - description: Application health has degraded
          when: app.status.health.status in ['Degraded'] and  time.Now().Sub(time.Parse(app.status.health.lastTransitionTime)).Minutes() >= 2
          send:
          - on-health-degraded
```
